server.port=8090

#Database
spring.datasource.url=jdbc:postgresql://db:5432/market
spring.datasource.username=usabana
spring.datasource.password=usabana123

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect